### ISSUE TITLE
Template review feedback

### ISSUE THREAD

**Issue by praveena-pappu** [consentmanager/consentmanager_gtm#1]
Thanks for submitting a template to the gallery, there were a few issues in your template that needed to be resolved ahead of approving the template for the gallery.

1) encodeUri should be used on user provided values that are then used to create your url. This method returns an encoded Uniform Resource Identifier (URI) by escaping special characters. Returns a string that represents the provided string encoded as a URI.
let scriptUrl = 'https://'+ consentmanager_cdn +'/delivery/customcmp/'+ consentmanager_id +'.js';

**Comment by FlipundFlop** [comment]
Hello,

thanks for getting back to me. We missed that encoding by accident. I just updated the project!

Best,

André

**Comment by praveena-pappu** [comment]
Hello,

Please refer to [encodeUri](https://developers.google.com/tag-manager/templates/api/#encodeuri) related information to encode the URL while creating the URL. Please do the changes accordingly in the template.

**Comment by FlipundFlop** [comment]
Hello, 

please check sha: 0d69525.

As i tried to use encodeUri we were not able to save the template ion the template editor cause encodeUri is always detected as undeclared variable. But refering to the documentation link you send encodeUriComponent ism the right encoding to use in this case.

Thanks for checking,

André
