### ISSUE TITLE
new version throws exception ("substr is not a function")

### ISSUE THREAD

**Issue by mbaersch** [consentmanager/consentmanager_gtm#2]
After updating the template I noticed that the cmpEvent was missing and then took a look at the template code editor. It seems that the added check for protocols in the domain fields fails. 

The original code throws the following exception when run in the editor: *"TypeError: substr is not a function"*

I had to change the lines  `if(consentmanager_cdn.substr(0,8) == 'https://')` and `if(consentmanager_host.substr(0,8) == 'https://')` to use `substring()` instead in order to make the new template work.

**Comment by janwinkler** [comment]
thanks for your feedback. i'Ve updated it to substring and added a string verification to it
